version: '3'
services:
  nextjs-app:
    container_name: nextjs-app
    image: docker-reg.dipro-tech.com/tokiwagi:${TAG}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.env
    ports:
      - '3000:3000'
    volumes:
      - '/data/logs:/app/logs'
    restart: always
